<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.netty.contrib</groupId>
        <artifactId>netty-codec-multipart-parent</artifactId>
        <version>5.0.0.Alpha2-SNAPSHOT</version>
    </parent>

    <artifactId>netty-codec-multipart-core</artifactId>
    <version>${project.parent.version}</version>
    <name>Netty/Contrib/Multipart/Core</name>
    <packaging>jar</packaging>

    <properties>
        <javaModuleName>io.netty.contrib.multipart</javaModuleName>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty5-codec-http</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty5-common</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty5-buffer</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty5-transport</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty5-codec</artifactId>
            <version>${netty.version}</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <!-- To run jazzer directly (i.e. not through jazzer-junit), use this profile and supply the
        jazzer_standalone.jar from the jazzer distribution. -->
        <profile>
            <id>direct-fuzzing</id>

            <dependencies>
                <dependency>
                    <groupId>jazzer-runtime</groupId>
                    <artifactId>jazzer-runtime</artifactId>
                    <version>${jazzer.version}</version>
                    <systemPath>${JAZZER_STANDALONE}</systemPath>
                    <scope>system</scope>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
</project>
