<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.netty.contrib</groupId>
    <artifactId>netty-codec-multipart-parent</artifactId>
    <version>1.0.1.Final-SNAPSHOT</version>
  </parent>

  <artifactId>netty-codec-multipart-vintage</artifactId>
  <version>1.0.1.Final-SNAPSHOT</version>
  <name>Netty/Contrib/Multipart/Vintage</name>
  <packaging>jar</packaging>

  <properties>
    <javaModuleName>io.netty.contrib.multipart.vintage</javaModuleName>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.netty.contrib</groupId>
      <artifactId>netty-codec-multipart-core</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.code-intelligence</groupId>
      <artifactId>jazzer-junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut.fuzzing</groupId>
      <artifactId>micronaut-fuzzing-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.27.3</version>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <profiles>
    <!-- To run jazzer directly (i.e. not through jazzer-junit), use this profile and supply the
    jazzer_standalone.jar from the jazzer distribution. -->
    <profile>
      <id>direct-fuzzing</id>

      <dependencies>
        <dependency>
          <groupId>jazzer-runtime</groupId>
          <artifactId>jazzer-runtime</artifactId>
          <version>${jazzer.version}</version>
          <systemPath>${JAZZER_STANDALONE}</systemPath>
          <scope>system</scope>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
</project>
